{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # DYNAMIC NAME: Becomes "wanthave-backend"
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    # Sticky sessions (Useful for Django Admin or sessions without Redis)
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "WANTHAVE_BACKEND"
    nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
    # Optional: Increase body size for file uploads
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # DYNAMIC SERVICE NAME
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts: [ {{ .Values.ingress.host | quote }} ]
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}