defaultNamespace: wanthave-fleet
helm:
  releaseName: wanthave-backend
targetCustomizations:
  - name: prod
    namespace: wanthave-fleet
    clusterSelector:
      matchLabels: {}
    helm:
      values:
        ingress:
          host: wanthave-fleet-api.kub2.fh-joanneum.at
        image:
          imagePullSecret: wanthave-fleet-token
        secretName: wanthave-fleet-secrets
