defaultNamespace: wanthave-fleet-dev
helm:
  releaseName: wanthave-backend-dev
targetCustomizations:
  - name: dev
    namespace: wanthave-fleet-dev
    clusterSelector:
      matchLabels: {}
    helm:
      values:
        ingress:
          host: dev.wanthave-fleet-api.kub2.fh-joanneum.at
        image:
          imagePullSecret: dev-wanthave-token
        secretName: dev-wanthave-fleet-secrets
        appEnv:
          - name: DJANGO_ALLOWED_HOSTS
            value: "*"
          - name: DEBUG
            value: "False"
          - name: SQLITE_DB_PATH
            value: "/data/db.sqlite3"
          - name: REDIS_HOST
            value: "redis.wanthave-fleet"
          - name: MEDIA_ROOT
            value: "/data/media"
