# Values for DEV environment
namespace: wanthave-dev

image:
  imagePullSecret: dev-wanthave-argotoken

ingress:
  host: dev-wanthave-api.kub2.fh-joanneum.at
  tls:
    secretName: dev-wanthave-api-tls

# Override secret name for Dev environment
secretName: dev-wanthave-secrets

# Point to Redis in the PROD namespace (and restore other env vars)
appEnv:
  - name: DJANGO_ALLOWED_HOSTS
    value: "*"
  - name: DEBUG
    value: "True" # Useful for Dev
  - name: SQLITE_DB_PATH
    value: "/data/db.sqlite3"
  - name: REDIS_HOST
    # Override: Connect to Redis in 'wanthave' namespace
    value: "redis.wanthave.svc.cluster.local"
  - name: MEDIA_ROOT
    value: "/data/media"
  - name: BACKEND_URL
    value: "https://dev-wanthave-api.kub2.fh-joanneum.at"