defaultNamespace: wanthave-fleet
helm:
  releaseName: wanthave-frontend
targetCustomizations:
  - name: prod
    namespace: wanthave-fleet
    clusterSelector:
      matchLabels: {}
    helm:
      values:
        ingress:
          host: wanthave-fleet.kub2.fh-joanneum.at
        image:
          imagePullSecret: wanthave-fleet-token
