defaultNamespace: wanthave-fleet
helm:
  releaseName: wanthave-frontend
targets:
  - clusterSelector: {}
    helm:
      values:
        ingress:
          host: wanthave-fleet.kub2.fh-joanneum.at
        image:
          imagePullSecret: wanthave-fleet-token
